# Generated by Django 5.0.2 on 2025-07-05 16:54

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=applications.models.phone_image_path),
        ),
    ]
