# Generated by Django 5.0.2 on 2025-07-05 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_phone_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='phone_price',
        ),
        migrations.RemoveField(
            model_name='application',
            name='selected_phone',
        ),
        migrations.CreateModel(
            name='ApplicationPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_phones', to='applications.application')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.phone')),
            ],
            options={
                'unique_together': {('application', 'phone')},
            },
        ),
    ]
