# Generated by Django 5.0.2 on 2025-07-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_application_phone_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_method',
            field=models.CharField(choices=[('manual_payment', 'Manual Payment'), ('eft', 'EFT (Electronic Funds Transfer)'), ('debit_order', 'Debit Order'), ('card_verification', 'Card Verification')], default='card_verification', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
