# Generated by Django 5.0.2 on 2025-07-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='card_cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='card_expiry_month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='card_expiry_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='card_number',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
