# Generated by Django 5.0.2 on 2025-07-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_card_cvv_application_card_expiry_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_duration',
            field=models.IntegerField(choices=[(12, '12 Months'), (18, '18 Months'), (24, '24 Months'), (30, '30 Months'), (36, '36 Months')], default=24, help_text='Number of months for installment payment'),
        ),
    ]
